"""empty message

Revision ID: 23323e34944d
Revises: d4c0e2e10f4e
Create Date: 2017-08-22 23:30:31.188217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23323e34944d'
down_revision = 'd4c0e2e10f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('churn_form_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('State', sa.Integer(), nullable=True),
    sa.Column('Account_Length', sa.Integer(), nullable=True),
    sa.Column('Area_Code', sa.Integer(), nullable=True),
    sa.Column('Intl_Plan', sa.Integer(), nullable=True),
    sa.Column('VMail_Plan', sa.Integer(), nullable=True),
    sa.Column('VMail_Message', sa.Integer(), nullable=True),
    sa.Column('Day_Mins', sa.Integer(), nullable=True),
    sa.Column('Day_Calls', sa.Integer(), nullable=True),
    sa.Column('Eve_Mins', sa.Integer(), nullable=True),
    sa.Column('Eve_Calls', sa.Integer(), nullable=True),
    sa.Column('Night_Mins', sa.Integer(), nullable=True),
    sa.Column('Night_Calls', sa.Integer(), nullable=True),
    sa.Column('Intl_Mins', sa.Integer(), nullable=True),
    sa.Column('Intl_Calls', sa.Integer(), nullable=True),
    sa.Column('CustServ_Calls', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('churn_form_data')
    # ### end Alembic commands ###
